name: travel_near_me
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  google_maps_flutter: ^2.6.1
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  google_places_flutter: ^2.0.8
  http: ^1.2.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_riverpod: ^2.5.1
  flutter_spinkit: ^5.2.1
  flutter_polyline_points_plus: ^3.0.0
  flutter_svg: ^2.0.10+1
  sleek_circular_slider: ^2.0.1
  audioplayers: ^6.0.0
  location: ^6.0.2
  flutter_local_notifications: ^17.1.2
  permission_handler: ^11.3.1
  vibration: ^1.9.0
  logger: ^2.3.0
  flutter_background_service: ^5.0.6
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0

flutter:
  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/
    - assets/icon/
    - assets/sounds/


  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
